### ISSUE TITLE
consider ensuring argv._ is always set

### ISSUE THREAD

**Issue by timkuijsten** [astur/oopt#2]
Would you consider always setting the operands array so that I don't have to check whether or not it exists before I check the length of it?

I currently have code like the following:
```js
var argv = oopt('sq:');

if (argv._.length < 3 || argv._.length > 4) {
  printusage(process.stderr);
  process.exit(1);
}
```

But this fails if the command is run without operands since argv._ does not exist in that case.
```sh
if (argv._.length < 3 || argv._.length > 4) {
          ^

TypeError: Cannot read property 'length' of undefined
```

Proposed patch:
```patch
diff --git a/index.js b/index.js
index f68de16..2818a20 100644
--- a/index.js
+++ b/index.js
@@ -9,7 +9,7 @@ module.exports = (optstring, args = process.argv.slice(2)) => {
     if(/::/.test(optstring)) throw new Error('double colons are not allowed');
     if(/([a-zA-Z0-9])(.*)\1/.test(optstring)) throw new Error('repeating options are not allowed');
 
-    const result = {};
+    const result = { _: [] };
 
     for(let i = 0, l = optstring.length; i < l; i++){
         if(optstring[i + 1] === ':'){
```

**Comment by astur** [comment]
I was thinking about this idea for weeks. It is really attractive. But now it is late to change this functionality.

I know many projects (including a couple of mine) with code like this:

```js
if(argv._){
    doSomethingWith(argv._);
}

// or like this:

const operands = argv._ || ['default', 'operands', 'list'];
```

Your patch will break this code.

oopt is small and easy project. Support for two major versions is too hard for it.
